Test (#1)
* test DB init using empty plus

* re-org

* test

* make executable

* remove empty_db.sh

* add debug

* use super-global

* look for my env vars

* back to getenv

* include myphpadmin and dump of DB

Co-authored-by: Ubuntu <wmo_admin@wmo-resolutions-test.ls0jvte4dcvubd2ski40ldyrzg.frax.internal.cloudapp.net>

diff --git a/.github/workflows/actions.yaml b/.github/workflows/actions.yaml
--- a/.github/workflows/actions.yaml
+++ b/.github/workflows/actions.yaml
@@ -7,22 +7,23 @@ jobs:
     - uses: actions/checkout@v2
     - name: docker-compose build
       run: docker-compose build
-    - name: docker-compose up
+    - name: docker-compose up (plus sleep)
       run: |
-          docker-compose up -d
-          sleep 10
-          docker ps
-    - name: grep "Error"
+        docker-compose up -d
+        sleep 10
+        docker ps
+    - name: check web-output looks correct
       run: | 
-        if curl -s localhost:8080 | grep -q "Error" ; then
-          docker logs resolutions-php_web_1
-          docker logs resolutions-php_db_1
+        curl -s localhost:80 /tmp/output.html
+        if cat /tmp/output.html | grep -q "Error" ; then
+          echo "Error detected in web-output"
           exit 1 
         fi
-    - name: grep "Failed to connect to MySQL"
-      run: | 
-        if curl -s localhost:8080 | grep -q "Failed to connect to MySQL" ; then
-          docker logs resolutions-php_web_1
-          docker logs resolutions-php_db_1
+        if cat /tmp/output.html | grep -q "Failed to connect to MySQL" ; then
+          echo "Failed  MySQL detected in web-output"
           exit 1 
+        fi
+        if (( $(cat /tmp/output.html | grep -c '</option>') < 100 )); then
+          echo "Number of generated option-tags < 100, seems suspiciously low"
+          exit 1
         fi
